---
mount_volume_claim: nginx-html
file_path: index.html
app_name: vol-corrupter


# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false
