---
daemonset:
  app_name: hello-daemonset

replicaset:
  app_name: frontend
  replicas: 3

statefulset:
  app_name: hello
  replicas: 1

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false

