---
- name: Check Role
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: "{{ role_api }}"
    kind: Role
    namespace: "{{ namespace }}"
    name: "{{ test_rolename }}"
  register: rolenm
  until: rolenm.resources | length > 0
  retries: 30

- name: Check RoleBinding
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: "{{ rolebinding_api }}"
    kind: RoleBinding
    name: "{{ rolebinding_name }}"
    namespace: "{{ namespace }}"
  register: role_binding
  until: role_binding.resources | length > 0
  retries: 30

- name: Verify RoleBinding references expected role namespace
  fail:
    msg: Wrong namespace in rolebinding roleRef
  when: role_binding.resources[0].get('roleRef', {}).get('namespace', namespace) != namespace and role_binding.resources[0].get('roleRef', {}).get('namespace') is defined

- name: Verify RoleBinding references expected subject namespace
  fail:
    msg: Wrong namespace in rolebinding service account
  when: role_binding.resources[0].get('subjects')[0].get('namespace', '') != namespace
