---
app_name: cassandra
storage_size: 1Gi
number_of_replicas: 3
storage_class: ""
accessmode: ReadWriteOnce
image_path: quay.io/migqe/cassandra:multiarch

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false
