---
project_region: west_region
project_label: ocp-24686-label

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false

