---
num_pods: 1
default_replicas: "{{ num_pods }}"
default_app_name: simple-nginx-nopv

# Container listens on this port (see deployment template)
nginx_http_port: 8080

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false

