---
num_visits: 5
storage_size: 1Gi
mysql_image: mysql:8.0
cakephp_image: shinsenter/cakephp5:latest
node_port: 30080

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false
