---
- name: Delete Redis deployment
  k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete Redis service
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete Redis secret
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete Redis PVC
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ app_name }}-data"
        namespace: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Remove namespace
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
    wait_timeout: 600
  when: non_admin_user | bool == false
