---
app_name: nginx
storage_size: 1Gi
num_visits: 1

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_deploy: false
with_cleanup: false
with_validate: false
with_delete_deployment: false
with_delete_pvcs: false


logs_accessmode: ReadWriteOnce
html_accessmode: ReadWriteOnce
