---
app_name: mssql
storage_class: ""
accessmode: ReadWriteOnce

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_deploy: false
with_cleanup: false
with_validate: false

create_dummy_scc: false
dummy_scc: mssql-example-scc
