---
- name: Delete fsGroup deployment
  k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    context: "{{ context | default(omit) }}"
    host: "{{ server if (token | default('') | string | length) > 0 else omit }}"
    api_key: "{{ token if (token | default('') | string | length) > 0 else omit }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete PVC
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ app_name }}-pvc"
        namespace: "{{ namespace }}"
    context: "{{ context | default(omit) }}"
    host: "{{ server if (token | default('') | string | length) > 0 else omit }}"
    api_key: "{{ token if (token | default('') | string | length) > 0 else omit }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Remove namespace
  k8s:
    context: "{{ context | default(omit) }}"
    host: "{{ server if (token | default('') | string | length) > 0 else omit }}"
    api_key: "{{ token if (token | default('') | string | length) > 0 else omit }}"
    verify_ssl: "{{ verify_ssl }}"
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: yes
    wait_timeout: 600
  when: non_admin_user == false
