---
app_name: basic-pod
storage_size: 1Gi

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_deploy: false
with_cleanup: false
with_validate: false


accessmode: ReadWriteOnce
