---
- name: Check pod status
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors:
      - app={{ app_name }}
    field_selectors:
      - status.phase=Running
  register: pod
  until: >-
    pod.resources|default([])|length > 0 and
    pod | json_query('resources[*].status.containerStatuses[*].ready') | flatten |difference( [true] ) | length  == 0
  retries: 30

- name: Check for user files (excluding lost+found)
  kubernetes.core.k8s_exec:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    namespace: "{{ namespace }}"
    pod: "{{ (pod.resources | first).metadata.name }}"
    container: test-container
    command: /bin/sh -c 'find /data -type f'
  register: output

- debug:
    msg: "{{ output.stdout }}"

- fail:
    msg: "Expected no user files in /data (lost+found is ignored)"
  when: output.stdout != ''
