---
app_name: redis
redis_password: "PASSWORD"
redis_version: "latest"
storage_size: 1Gi
storage_class: ""
accessmode: ReadWriteOnce
redis_image: redis:latest

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false
