---
pvc_name: test-pvc
storage_size: 1Gi
storage_class: ""
accessmode: ReadWriteOnce

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false
