---
rolebinding_name: basic-role-binding
test_rolename: basic-role

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false

role_api: "rbac.authorization.k8s.io/v1"
rolebinding_api: "rbac.authorization.k8s.io/v1"
